config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :responses
  # resources :polls, only: :index
  # resources :polls, only: [:index, :create]
  resources :polls, except: %i[new edit]
  resources :users, only: %i[create index]
  resource :sessions, only: [:create, :destroy]

  root 'home#index'
  get '*path', to: 'home#index', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
    has_many :responses, dependent: :destroy
    has_many :votes, dependent: :destroy
    belongs_to :user
    validates :title, presence: true, length: { maximum: 50 }
    accepts_nested_attributes_for :responses
end

app/models/response.rb
class Response < ApplicationRecord
    belongs_to :poll
    has_many :votes, dependent: :destroy
    validates :option, presence: true, length: { maximum: 35 }
end

app/models/user.rb
class User < ApplicationRecord
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i.freeze

    has_many :polls, dependent: :destroy
    has_many :responses, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_secure_password
    has_secure_token :authentication_token
    
    
    validates :name, presence: true, length: { maximum: 35 }
    validates :email, presence: true,
                    uniqueness: true,
                    length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX }

    validates :password, presence: true, confirmation: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true, on: :create

    private

    def to_lowercase
      email.downcase!
    end

end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :user
    belongs_to :poll
    belongs_to :response,optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session

    def authenticate_user_using_x_auth_token
        user_email = request.headers["X-Auth-Email"]
        auth_token = request.headers["X-Auth-Token"].presence
        user = user_email && User.find_by_email(user_email)
    
        if user && auth_token &&
          ActiveSupport::SecurityUtils.secure_compare(
            user.authentication_token, auth_token
          )
          @current_user = user
        else
            render status: :unauthorized, json: { errors: [t('session.could_not_auth')] }
        end
    end
    
    private
    
    def current_user
        @current_user 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user_using_x_auth_token, except: [:index]
  before_action :load_poll, only: %i[show update destroy]
  before_action :load_responses, :load_votes, only: %i[show]

    def index
        polls = Poll.all
        render status: :ok, json: {polls: polls}
    end

    def create
        @poll = Poll.new(poll_params.merge(user_id: @current_user.id))
  
        if @poll.save
          render status: :ok, json: { notice: t('successfully_created', entity: 'Poll') }
        else
          errors = @poll.errors.full_messages
          render status: :unprocessable_entity, json: { errors: errors  }
        end
    end

    def show
      render status: :ok, json: {  poll: @poll, responses: @responses, votes: @votes }
    end

    def update
      if @poll.update(poll_params)
        render status: :ok, json: {  }
      else
        render status: :unprocessable_entity, json: { errors: @poll.errors.full_messages }
      end
    end

    def destroy
      if @poll.destroy
        render status: :ok, json: { notice: 'Successfully deleted task.' }
      else
        render status: :unprocessable_entity, json: { errors:
        @poll.errors.full_messages }
      end
    end

    private

    def poll_params
      params.require(:poll).permit(:title, responses_attributes: [:id, :option])
    end

      
    def load_poll
      @poll = Poll.find(params[:id])
      rescue ActiveRecord::RecordNotFound => errors
        render json: {errors: errors }
    end 

    def load_responses
      @responses = Response.where(poll_id: params[:id]).limit(4)

    rescue ActiveRecord::RecordNotFound => errors
      render json: {errors: errors }
    end
  
    def load_votes
      @votes = Vote.where(poll_id: params[:id])
      rescue ActiveRecord::RecordNotFound => errors
        render json: {errors: errors}
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :authenticate_user_using_x_auth_token, only: [:destroy]

    def create
        user = User.find_by(email: login_params[:email].downcase)
        if user.present? && user.authenticate(login_params[:password])
          render status: :ok, json: { auth_token: user.authentication_token, userId: user.id ,user_name: user.name}
        else
            render status: :unauthorized, json: { notice: t('session.incorrect_credentials') }
        end
    end

    def destroy
        @current_user = nil
    end
    
      private
    
        def login_params
          params.require(:login).permit(:email, :password)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    def index
      users = User.all.as_json(only: %i[id name])
      render status: :ok, json: { users: users }
    end
  
    def create
        @user = User.new(user_params)
        if @user.save
            render status: :ok, json: { notice: 'successfully_created' }
        else
          render status: :unprocessable_entity, json: {
            errors: @user.errors.full_messages.to_sentence
          }
        end
      end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end  

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user_using_x_auth_token, only: %i[create]
  before_action :check_vote_existance, only: %i[create]

  def create
    @vote = Vote.new(vote_params)
    if @vote.save
      render status: :ok, json: { vote: @vote, notice: 'Voted Successfully!' }
    else
      errors = @vote.errors.full_messages
      render status: :unprocessable_entity, json: { errors: errors }    
    end
  end
  
  private 

  def vote_params
    params.require(:vote).permit(:poll_id, :response_id).merge(user_id: @current_user.id)
  end

  def check_vote_existance
    vote = Vote.where(poll_id: vote_params[:poll_id], user_id: @current_user.id)
    if vote.length > 0
      render status: :unprocessable_entity, json: {
        errors: "Voted Already -_- "
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/home/index.html.erb
<%= react_component 'App' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/responses/_form.html.erb
<%= form_with(model: response) do |form| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
        <% response.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :option %>
    <%= form.text_field :option %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses</h1>

<table>
  <thead>
    <tr>
      <th>Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.option %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Option:</strong>
  <%= @response.option %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>

app/views/votes/_form.html.erb
<%= form_with(model: vote) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
        <% vote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :poll_id %>
    <%= form.number_field :poll_id %>
  </div>

  <div class="field">
    <%= form.label :option_id %>
    <%= form.number_field :option_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Poll</th>
      <th>Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user_id %></td>
        <td><%= vote.poll_id %></td>
        <td><%= vote.option_id %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote.user_id %>
</p>

<p>
  <strong>Poll:</strong>
  <%= @vote.poll_id %>
</p>

<p>
  <strong>Option:</strong>
  <%= @vote.option_id %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>